force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main point of contact for the role</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Application</relationshipLabel>
    <relationshipName>Job_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SetPrimaryContactQueueable.cls
public with sharing class SetPrimaryContactQueueable implements Queueable {
    private List<Id> jobAppIds;
    
    public SetPrimaryContactQueueable(List<Id> jobAppIds) {
        this.jobAppIds = jobAppIds;
    }

    public void execute(QueueableContext context) {
        List<Job_Application__c> jobAppList = [
            SELECT Id, Primary_Contact__c, Company_Name__c
            FROM Job_Application__c
            WHERE Id IN :jobAppIds
        ];

        JobApplicationHelper.setPrimaryContact(jobAppList);

        update jobAppList;
    }
}